import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-slate-950 via-black to-gray-900`}
      >
        <div className="w-72 p-4 mt-4 mx-auto flex justify-between gap-4 row-start-1 bg-gradient-to-r from-[#0070f3] to-[#7928ca] text-background rounded-full text-sm text-slate-300">
          <Link href={'/'} className="hover:underline active:underline underline-offset-8 font-semibold *:hover:underline-offset-8 hover:scale-105">
            Home
          </Link>
          <Link href='/todos' className="hover:underline active:underline underline-offset-8 font-semibold *:hover:underline-offset-8 hover:scale-105">
            Posts
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
